/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.ControladorJuego;
import modelo.Nivel;

/**
 *
 * @author efrai
 */
public class FrmJuego extends javax.swing.JFrame {
    
   private javax.swing.JButton[] botonesPrincipiante;
   private ControladorJuego controlador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmJuego.class.getName());

    /**
     * Creates new form FrmJuego
     */
    public FrmJuego() {
        initComponents();
        
        botonesPrincipiante= new javax.swing.JButton[16];
        
        botonesPrincipiante[0]=btnP1;
        botonesPrincipiante[1]=btnP2;
        botonesPrincipiante[2]=btnP3;
        botonesPrincipiante[3]=btnP4;
        botonesPrincipiante[4]=btnP5;
        botonesPrincipiante[5]=btnP6;
        botonesPrincipiante[6]=btnP7;
        botonesPrincipiante[7]=btnP8;
        botonesPrincipiante[8]=btnP9;
        botonesPrincipiante[9]=btnP10;
        botonesPrincipiante[10]=btnP11;
        botonesPrincipiante[11]=btnP12;
        botonesPrincipiante[12]=btnP13;
        botonesPrincipiante[13]=btnP14;
        botonesPrincipiante[14]=btnP15;
        botonesPrincipiante[15]=btnP16;
        
        controlador=new ControladorJuego(Nivel.PRINCIPIANTE,this);
        mostrarTableroSegunNIvel();
       setLocationRelativeTo(null);
    }
    
    public void mostrarTableroSegunNIvel(){
        int opcion;
        opcion=cmbNivel.getSelectedIndex();
        
        pnlPrincipiante.setVisible(false);
        pnlIntermedio.setVisible(false);
        pnlAvanzado.setVisible(false);
        if(opcion==0){
            pnlPrincipiante.setVisible(true);
        }else if(opcion== 1){
            pnlIntermedio.setVisible(true);
        }else if(opcion==2){
            pnlAvanzado.setVisible(true);
        }
    }
    public void seleccionarCarta(int fila, int columna){
        controlador.seleccionarCarta(fila, columna);  
    }
     public void reiniciarValores() {

    lblPuntajeValor.setText("0");
    lblIntentosValor.setText("0");
    lblParejasValor.setText("0");
    lblTiempoValor.setText("00:00");
}
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlTablero = new javax.swing.JPanel();
        pnlPrincipiante = new javax.swing.JPanel();
        btnP1 = new javax.swing.JButton();
        btnP2 = new javax.swing.JButton();
        btnP3 = new javax.swing.JButton();
        btnP4 = new javax.swing.JButton();
        btnP5 = new javax.swing.JButton();
        btnP6 = new javax.swing.JButton();
        btnP7 = new javax.swing.JButton();
        btnP8 = new javax.swing.JButton();
        btnP9 = new javax.swing.JButton();
        btnP10 = new javax.swing.JButton();
        btnP11 = new javax.swing.JButton();
        btnP12 = new javax.swing.JButton();
        btnP13 = new javax.swing.JButton();
        btnP14 = new javax.swing.JButton();
        btnP15 = new javax.swing.JButton();
        btnP16 = new javax.swing.JButton();
        pnlIntermedio = new javax.swing.JPanel();
        pnlAvanzado = new javax.swing.JPanel();
        pnlInformacion = new javax.swing.JPanel();
        lblTiempo = new javax.swing.JLabel();
        cmbNivel = new javax.swing.JComboBox<>();
        lblPuntajeValor = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblTiempoValor = new javax.swing.JLabel();
        lblPuntaje = new javax.swing.JLabel();
        lblIntentosValor = new javax.swing.JLabel();
        lblParejas = new javax.swing.JLabel();
        lblParejasValor = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 750));
        setResizable(false);

        pnlTablero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTablero.setMinimumSize(new java.awt.Dimension(600, 350));
        pnlTablero.setPreferredSize(new java.awt.Dimension(1000, 500));
        pnlTablero.setLayout(new java.awt.CardLayout());

        pnlPrincipiante.setLayout(new java.awt.GridLayout(4, 4));

        btnP1.addActionListener(this::btnP1ActionPerformed);
        pnlPrincipiante.add(btnP1);

        btnP2.addActionListener(this::btnP2ActionPerformed);
        pnlPrincipiante.add(btnP2);

        btnP3.addActionListener(this::btnP3ActionPerformed);
        pnlPrincipiante.add(btnP3);

        btnP4.addActionListener(this::btnP4ActionPerformed);
        pnlPrincipiante.add(btnP4);

        btnP5.addActionListener(this::btnP5ActionPerformed);
        pnlPrincipiante.add(btnP5);

        btnP6.addActionListener(this::btnP6ActionPerformed);
        pnlPrincipiante.add(btnP6);

        btnP7.addActionListener(this::btnP7ActionPerformed);
        pnlPrincipiante.add(btnP7);

        btnP8.addActionListener(this::btnP8ActionPerformed);
        pnlPrincipiante.add(btnP8);

        btnP9.addActionListener(this::btnP9ActionPerformed);
        pnlPrincipiante.add(btnP9);

        btnP10.addActionListener(this::btnP10ActionPerformed);
        pnlPrincipiante.add(btnP10);

        btnP11.addActionListener(this::btnP11ActionPerformed);
        pnlPrincipiante.add(btnP11);

        btnP12.addActionListener(this::btnP12ActionPerformed);
        pnlPrincipiante.add(btnP12);

        btnP13.addActionListener(this::btnP13ActionPerformed);
        pnlPrincipiante.add(btnP13);

        btnP14.addActionListener(this::btnP14ActionPerformed);
        pnlPrincipiante.add(btnP14);

        btnP15.addActionListener(this::btnP15ActionPerformed);
        pnlPrincipiante.add(btnP15);

        btnP16.addActionListener(this::btnP16ActionPerformed);
        pnlPrincipiante.add(btnP16);

        pnlTablero.add(pnlPrincipiante, "card2");

        javax.swing.GroupLayout pnlIntermedioLayout = new javax.swing.GroupLayout(pnlIntermedio);
        pnlIntermedio.setLayout(pnlIntermedioLayout);
        pnlIntermedioLayout.setHorizontalGroup(
            pnlIntermedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        pnlIntermedioLayout.setVerticalGroup(
            pnlIntermedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        pnlTablero.add(pnlIntermedio, "card3");

        javax.swing.GroupLayout pnlAvanzadoLayout = new javax.swing.GroupLayout(pnlAvanzado);
        pnlAvanzado.setLayout(pnlAvanzadoLayout);
        pnlAvanzadoLayout.setHorizontalGroup(
            pnlAvanzadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        pnlAvanzadoLayout.setVerticalGroup(
            pnlAvanzadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        pnlTablero.add(pnlAvanzado, "card4");

        pnlInformacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlInformacion.setMaximumSize(new java.awt.Dimension(32767, 170));
        pnlInformacion.setMinimumSize(new java.awt.Dimension(600, 170));
        pnlInformacion.setPreferredSize(new java.awt.Dimension(1000, 170));

        lblTiempo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTiempo.setText("Tiempo:");

        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRINCIPIANTE", "INTERMEDIO", "AVANZADO" }));
        cmbNivel.addActionListener(this::cmbNivelActionPerformed);

        lblPuntajeValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPuntajeValor.setText("0");

        lblNivel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNivel.setText("Nivel:");

        lblTiempoValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTiempoValor.setText("00:00");

        lblPuntaje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPuntaje.setText("Puntaje:");

        lblIntentosValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIntentosValor.setText("0");

        lblParejas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblParejas.setText("Parejas Encontradas:");

        lblParejasValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblParejasValor.setText("0");

        lblIntentos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIntentos.setText("Intentos:");

        btnReiniciar.setText("REINICIAR");
        btnReiniciar.addActionListener(this::btnReiniciarActionPerformed);

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addComponent(lblNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addComponent(lblIntentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntentosValor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 569, Short.MAX_VALUE)
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addComponent(lblPuntaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntajeValor))
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addComponent(lblParejas, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblParejasValor)))
                .addGap(188, 188, 188)
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addComponent(lblTiempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTiempoValor))
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbNivel)
                                .addComponent(lblNivel))
                            .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTiempoValor)
                                .addComponent(lblTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInformacionLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIntentos)
                                    .addComponent(lblIntentosValor))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionLayout.createSequentialGroup()
                        .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuntajeValor)
                            .addComponent(lblPuntaje))
                        .addGap(56, 56, 56)
                        .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblParejasValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblParejas))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTablero, javax.swing.GroupLayout.DEFAULT_SIZE, 1504, Short.MAX_VALUE)
            .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 1504, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        reiniciarValores();
        
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void cmbNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNivelActionPerformed
        mostrarTableroSegunNIvel();
    }//GEN-LAST:event_cmbNivelActionPerformed

    private void btnP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP1ActionPerformed
        seleccionarCarta(0,0);
    }//GEN-LAST:event_btnP1ActionPerformed

    private void btnP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2ActionPerformed
        seleccionarCarta(0,1);
    }//GEN-LAST:event_btnP2ActionPerformed

    private void btnP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP3ActionPerformed
        seleccionarCarta(0,2);
    }//GEN-LAST:event_btnP3ActionPerformed

    private void btnP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP4ActionPerformed
        seleccionarCarta(0,3);
    }//GEN-LAST:event_btnP4ActionPerformed

    private void btnP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP5ActionPerformed
        seleccionarCarta(1,0);
    }//GEN-LAST:event_btnP5ActionPerformed

    private void btnP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP6ActionPerformed
        seleccionarCarta(1,1);
    }//GEN-LAST:event_btnP6ActionPerformed

    private void btnP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP7ActionPerformed
        seleccionarCarta(1,2);
    }//GEN-LAST:event_btnP7ActionPerformed

    private void btnP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP8ActionPerformed
        seleccionarCarta(1,3);
    }//GEN-LAST:event_btnP8ActionPerformed

    private void btnP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP9ActionPerformed
        seleccionarCarta(2,0);
    }//GEN-LAST:event_btnP9ActionPerformed

    private void btnP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP10ActionPerformed
        seleccionarCarta(2,1);
    }//GEN-LAST:event_btnP10ActionPerformed

    private void btnP11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP11ActionPerformed
        seleccionarCarta(2,2);
    }//GEN-LAST:event_btnP11ActionPerformed

    private void btnP12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP12ActionPerformed
        seleccionarCarta(2,3);
    }//GEN-LAST:event_btnP12ActionPerformed

    private void btnP13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP13ActionPerformed
        seleccionarCarta(3,0);
    }//GEN-LAST:event_btnP13ActionPerformed

    private void btnP14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP14ActionPerformed
        seleccionarCarta(3,1);
    }//GEN-LAST:event_btnP14ActionPerformed

    private void btnP15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP15ActionPerformed
        seleccionarCarta(3,2);
    }//GEN-LAST:event_btnP15ActionPerformed

    private void btnP16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP16ActionPerformed
        seleccionarCarta(3,3);
    }//GEN-LAST:event_btnP16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmJuego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnP1;
    private javax.swing.JButton btnP10;
    private javax.swing.JButton btnP11;
    private javax.swing.JButton btnP12;
    private javax.swing.JButton btnP13;
    private javax.swing.JButton btnP14;
    private javax.swing.JButton btnP15;
    private javax.swing.JButton btnP16;
    private javax.swing.JButton btnP2;
    private javax.swing.JButton btnP3;
    private javax.swing.JButton btnP4;
    private javax.swing.JButton btnP5;
    private javax.swing.JButton btnP6;
    private javax.swing.JButton btnP7;
    private javax.swing.JButton btnP8;
    private javax.swing.JButton btnP9;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblIntentosValor;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblParejas;
    private javax.swing.JLabel lblParejasValor;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblPuntajeValor;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblTiempoValor;
    private javax.swing.JPanel pnlAvanzado;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JPanel pnlIntermedio;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlPrincipiante;
    private javax.swing.JPanel pnlTablero;
    // End of variables declaration//GEN-END:variables
}
